default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: lw-retro_development

test:
  <<: *default
  database: lw-retro_test

production:
  <<: *default
  database: lw-retro_production